---
- hosts: node0
  vars_files:
    - var.yml
  become: yes
  roles:
      - { role: geerlingguy.jenkins }
  tasks:
  - name: Install required system packages.
    become: yes
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: "{{ system_packages }}"
  - name: Install required pip packages.
    easy_install: name={{ item }}
    with_items: "{{ python_packages }}"
  - name: Install required Python packages.
    pip: name={{ item }}
    with_items: "{{ python_pip_packages }}"



